const artistas = [
  { "nombreArtista": "L-Gante", "cover": "L-Gante.webp" },
  { "nombreArtista": "La Joaqui", "cover": "La-Joaqui.webp" },
  { "nombreArtista": "Kaleb Di Masi", "cover": "Kaleb-Di-Masi.webp" },
  { "nombreArtista": "Callejero Fino", "cover": "Callejero-Fino.webp" },
  { "nombreArtista": "BM", "cover": "BM.webp" },
  { "nombreArtista": "Alan Gomez", "cover": "Alan-Gomez.webp" },
  { "nombreArtista": "Banda MS", "cover": "Banda-MS.webp" },
  { "nombreArtista": "Christian Nodal", "cover": "Christian-Nodal.webp" },
  { "nombreArtista": "Carín León", "cover": "Carin-Leon.webp" },
  { "nombreArtista": "Peso Pluma", "cover": "Peso-Pluma.webp" },
  { "nombreArtista": "Fumaratto", "cover": "Fumaratto.webp" },
  { "nombreArtista": "Marcela Reyes", "cover": "Marcela-Reyes.webp" },
  { "nombreArtista": "Víctor Cárdenas", "cover": "Victor-Cardenas.webp" },
  { "nombreArtista": "Soda Stereo", "cover": "Soda-Stereo.webp" },
  { "nombreArtista": "Enanitos Verdes", "cover": "Enanitos-Verdes.webp" },
  { "nombreArtista": "Héroes del Silencio", "cover": "Heroes-del-Silencio.webp" },
  { "nombreArtista": "Maná", "cover": "Mana.webp" },
  { "nombreArtista": "Café Tacvba", "cover": "Cafe-Tacvba.webp" },
  { "nombreArtista": "Aterciopelados", "cover": "Aterciopelados.webp" },
  { "nombreArtista": "Bad Bunny", "cover": "Bad-Bunny.webp" },
  { "nombreArtista": "Karol G", "cover": "Karol-G.webp" },
  { "nombreArtista": "J Balvin", "cover": "J-Balvin.webp" },
  { "nombreArtista": "Feid", "cover": "Feid.webp" },
  { "nombreArtista": "Rauw Alejandro", "cover": "Rauw-Alejandro.webp" },
  { "nombreArtista": "Myke Towers", "cover": "Myke-Towers.webp" },
  { "nombreArtista": "Diomedes Díaz", "cover": "Diomedes-Diaz.webp" },
  { "nombreArtista": "Silvestre Dangond", "cover": "Silvestre-Dangond.webp" },
  { "nombreArtista": "Binomio de Oro", "cover": "Binomio-de-Oro.webp" },
  { "nombreArtista": "Jorge Celedón", "cover": "Jorge-Celedon.webp" },
  { "nombreArtista": "Rafael Orozco", "cover": "Rafael-Orozco.webp" },
  { "nombreArtista": "Kaleth Morales", "cover": "Kaleth-Morales.webp" },
  { "nombreArtista": "Jorge Velosa", "cover": "Jorge-Velosa.webp" },
  { "nombreArtista": "Los Rolling Ruanas", "cover": "Los-Rolling-Ruanas.webp" },
  { "nombreArtista": "Shakira", "cover": "Shakira.webp" },
  { "nombreArtista": "Ricky Martin", "cover": "Ricky-Martin.webp" },
  { "nombreArtista": "Luis Miguel", "cover": "Luis-Miguel.webp" },
  { "nombreArtista": "Alejandro Sanz", "cover": "Alejandro-Sanz.webp" },
  { "nombreArtista": "Camilo", "cover": "Camilo.webp" },
  { "nombreArtista": "Sebastian Yatra", "cover": "Sebastian-Yatra.webp" },
  { "nombreArtista": "Joe Arroyo", "cover": "Joe-Arroyo.webp" },
  { "nombreArtista": "Marc Anthony", "cover": "Marc-Anthony.webp" },
  { "nombreArtista": "Grupo Niche", "cover": "Grupo-Niche.webp" },
  { "nombreArtista": "José José", "cover": "Jose-Jose.webp" },
  { "nombreArtista": "Camilo Sesto", "cover": "Camilo-Sesto.webp" },
  { "nombreArtista": "Ana Gabriel", "cover": "Ana-Gabriel.webp" },
  { "nombreArtista": "Myriam Hernández", "cover": "Myriam-Hernandez.webp" },
  { "nombreArtista": "Yuri", "cover": "Yuri.webp" },
  { "nombreArtista": "Rocío Dúrcal", "cover": "Rocio-Durcal.webp" },
  { "nombreArtista": "Bizarrap", "cover": "Bizarrap.webp" },
  { "nombreArtista": "Tiago PZK", "cover": "Tiago-PZK.webp" },
  { "nombreArtista": "Tini", "cover": "Tini.webp" },
  { "nombreArtista": "Lali", "cover": "Lali.webp" },
  { "nombreArtista": "Emilia", "cover": "Emilia.webp" },
  { "nombreArtista": "Manuel Turizo", "cover": "Manuel-Turizo.webp" },
  { "nombreArtista": "Daddy Yankee", "cover": "Daddy-Yankee.webp" },
  { "nombreArtista": "Don Omar", "cover": "Don-Omar.webp" },
  { "nombreArtista": "Tego Calderón", "cover": "Tego-Calderon.webp" },
  { "nombreArtista": "Wisin & Yandel", "cover": "Wisin-Yandel.webp" },
  { "nombreArtista": "Ivy Queen", "cover": "Ivy-Queen.webp" },
  { "nombreArtista": "Zion & Lennox", "cover": "Zion-Lennox.webp" },
  { "nombreArtista": "Arcángel", "cover": "Arcangel.webp" },
  { "nombreArtista": "El Alfa", "cover": "El-Alfa.webp" },
  { "nombreArtista": "Tokischa", "cover": "Tokischa.webp" },
  { "nombreArtista": "Rochy RD", "cover": "Rochy-RD.webp" },
  { "nombreArtista": "Chimbala", "cover": "Chimbala.webp" },
  { "nombreArtista": "Darío Gómez", "cover": "Dario-Gomez.webp" },
  { "nombreArtista": "Yeison Jiménez", "cover": "Yeison-Jimenez.webp" },
  { "nombreArtista": "Jessi Uribe", "cover": "Jessi-Uribe.webp" },
  { "nombreArtista": "Paola Jara", "cover": "Paola-Jara.webp" },
  { "nombreArtista": "Arelys Henao", "cover": "Arelys-Henao.webp" },
  { "nombreArtista": "Mr. Black", "cover": "Mr-Black.webp" },
  { "nombreArtista": "Kevin Flórez", "cover": "Kevin-Florez.webp" },
  { "nombreArtista": "Juan Luis Guerra", "cover": "Juan-Luis-Guerra.webp" },
  { "nombreArtista": "Wilfrido Vargas", "cover": "Wilfrido-Vargas.webp" },
  { "nombreArtista": "Elvis Crespo", "cover": "Elvis-Crespo.webp" },
  { "nombreArtista": "Proyecto Uno", "cover": "Proyecto-Uno.webp" },
  { "nombreArtista": "Eddy Herrera", "cover": "Eddy-Herrera.webp" },
  { "nombreArtista": "Sergio Vargas", "cover": "Sergio-Vargas.webp" },
  { "nombreArtista": "Greeicy", "cover": "Greeicy.webp" },
  { "nombreArtista": "Mike Bahía", "cover": "Mike-Bahia.webp" },
  { "nombreArtista": "Ryan Castro", "cover": "Ryan-Castro.webp" },
  { "nombreArtista": "Blessd", "cover": "Blessd.webp" },
  { "nombreArtista": "Grupo Frontera", "cover": "Grupo-Frontera.webp" },
  { "nombreArtista": "Eslabon Armado", "cover": "Eslabon-Armado.webp" },
  { "nombreArtista": "Danny Ocean", "cover": "Danny-Ocean.webp" },
  { "nombreArtista": "Dua Lipa", "cover": "Dua-Lipa.webp" },
  { "nombreArtista": "The Weeknd", "cover": "The-Weeknd.webp" },
  { "nombreArtista": "Miley Cyrus", "cover": "Miley-Cyrus.webp" },
  { "nombreArtista": "Harry Styles", "cover": "Harry-Styles.webp" },
  { "nombreArtista": "Bruno Mars", "cover": "Bruno-Mars.webp" },
  { "nombreArtista": "Marshmello", "cover": "Marshmello.webp" },
  { "nombreArtista": "Calvin Harris", "cover": "Calvin-Harris.webp" },
  { "nombreArtista": "David Guetta", "cover": "David-Guetta.webp" },
  { "nombreArtista": "Tiësto", "cover": "Tiesto.webp" },
  { "nombreArtista": "Alok", "cover": "Alok.webp" },
  { "nombreArtista": "Maluma", "cover": "Maluma.webp" },
  { "nombreArtista": "Ozuna", "cover": "Ozuna.webp" },
  { "nombreArtista": "Farruko", "cover": "Farruko.webp" },
  { "nombreArtista": "Natti Natasha", "cover": "Natti-Natasha.webp" },
  { "nombreArtista": "Becky G", "cover": "Becky-G.webp" }
];

export default artistas;