const generos = [
  { "nombre": "60s", "slug": "60s" },
  { "nombre": "70s", "slug": "70s" },
  { "nombre": "80s", "slug": "80s" },
  { "nombre": "90s", "slug": "90s" },
  { "nombre": "AFROBEAT", "slug": "afrobeat" },
  { "nombre": "BACHATA", "slug": "bachata" },
  { "nombre": "BANDA", "slug": "banda" },
  { "nombre": "CARNAVAL", "slug": "carnaval" },
  { "nombre": "CARRANGA", "slug": "carranga" },
  { "nombre": "CHAMPETA", "slug": "champeta" },
  { "nombre": "CIRCUIT", "slug": "circuit" },
  { "nombre": "CLUB", "slug": "club" },
  { "nombre": "CORRIDO TUMBAO", "slug": "corrido-tumbao" },
  { "nombre": "COUNTRY", "slug": "country" },
  { "nombre": "CUBATON", "slug": "cubaton" },
  { "nombre": "CUMBIA", "slug": "cumbia" },
  { "nombre": "DANCE HALL", "slug": "dance-hall" },
  { "nombre": "DEMBOW", "slug": "dembow" },
  { "nombre": "ELECTRO COMERCIAL", "slug": "electro-comercial" },
  { "nombre": "ELECTRO", "slug": "electro" },
  { "nombre": "GAY HITS", "slug": "gay-hits" },
  { "nombre": "GUARACHA", "slug": "guaracha" },
  { "nombre": "HIP HOP", "slug": "hip-hop" },
  { "nombre": "HUAPANGO", "slug": "huapango" },
  { "nombre": "LATINO", "slug": "latino" },
  { "nombre": "MAMBO", "slug": "mambo" },
  { "nombre": "MASHUP", "slug": "mashup" },
  { "nombre": "MERENGUE", "slug": "merengue" },
  { "nombre": "MEXICANO", "slug": "mexicano" },
  { "nombre": "MOOMBATHON", "slug": "moombathon" },
  { "nombre": "OTHER", "slug": "other" },
  { "nombre": "PLANCHA", "slug": "plancha" },
  { "nombre": "POP EN INGLES RETRO", "slug": "pop-en-ingles-retro" },
  { "nombre": "POP EN INGLES", "slug": "pop-en-ingles" },
  { "nombre": "POP LATINO DANCE", "slug": "pop-latino-dance" },
  { "nombre": "POP LATINO", "slug": "pop-latino" },
  { "nombre": "POPULAR", "slug": "popular" },
  { "nombre": "RAGGA", "slug": "ragga" },
  { "nombre": "RANCHERA", "slug": "ranchera" },
  { "nombre": "REGGAE", "slug": "reggae" },
  { "nombre": "REGGAETON OLD", "slug": "reggaeton-old" },
  { "nombre": "REGGAETON", "slug": "reggaeton" },
  { "nombre": "RETRO ESPAÑOL CLUB", "slug": "retro-espanol-club" },
  { "nombre": "RETRO INGLES CLUB", "slug": "retro-ingles-club" },
  { "nombre": "ROCK EN ESPAÑOL", "slug": "rock-en-espanol" },
  { "nombre": "ROCK EN INGLES", "slug": "rock-en-ingles" },
  { "nombre": "SALSA", "slug": "salsa" },
  { "nombre": "TRANSITION", "slug": "transition" },
  { "nombre": "TRAP", "slug": "trap" },
  { "nombre": "TROPICAL", "slug": "tropical" },
  { "nombre": "TROPIPOP", "slug": "tropipop" },
  { "nombre": "TWERK", "slug": "twerk" },
  { "nombre": "VALLENATO", "slug": "vallenato" }
]

export  default generos